import React from 'react'
import Head from 'next/head'

interface HeaderTitleType {
  title: string
}

const HeaderTitle = (props: HeaderTitleType) => {
  const { title } = props
  return (
    <Head>
      <title>
        {`${title} | MUI NEXT`}
      </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    </Head>
  )
}

export default HeaderTitle
